name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
          working-directory: docs
      - name: Build docs
        working-directory: docs
        run: cd docs && yarn build
      - name: Deploy docs
        env:
          GIT_USER: ravisuhag
          GIT_PASS: ${{ secrets.DOCU_RS_TOKEN }}
          DEPLOYMENT_BRANCH: gh-pages
          CURRENT_BRANCH: master
        working-directory: docs
        run: |
          git config --global user.email "suhag.ravi@gmail.com"
          git config --global user.name "ravisuhag"
          yarn deploy
